### PR TITLE
Added support for A&A (aanda class document)

### PR DESCRIPTION
**Pull request by BrunoSanchez**
Additional cls option `'aanda'` with support for A&A.

Can create document (`--doc` flag) and authorlist.tex using `-j aanda` option.

### CODE REVIEW

**Comment by BrunoSanchez** [comment]
This is solving enhancement proposed in issue #17

**Comment by kadrlica** [comment]
@BrunoSanchez thanks for this! Could you also write a test here:
https://github.com/DarkEnergySurvey/mkauthlist/blob/master/tests/test_journals.py
and post the pdf that comes out?

Should be a pretty simple extension of the existing tests.

**Comment by BrunoSanchez** [comment]
This is the pdf: 
[test_aanda.pdf](https://github.com/DarkEnergySurvey/mkauthlist/files/7047503/test_aanda.pdf)

**Comment by kadrlica** [comment]
Looks good! I've been able to clone and successfully run the tests. I think that at some point we may want to consider using the A&A tools for long author lists, but the complexity of that is what initially had me shy away from implementing A&A.

**Comment by BrunoSanchez** [comment]
Yes the A&A tools might be useful, but mkauthlist would have to decide when to use it based on number of authors. That's quite tricky and it would require some additional options in the CLI.

**Pull request merged**
