### PR TITLE
Fix spacing in arxiv format (and the build workflow)

### LINKED ISSUE #34: Spacing in arxiv format
We are replacing the latex spacing character `~` with a space in arxiv formatting. This is having the unintended effect of removing the tilde character, for example `\~n`. In addition, we should replace `.\ ` with `. `.

### PR DESCRIPTION
**Pull request by misharash**
These changes should fix #34:
* replace the tilde `~` with space **only if not preceded by the backslash** `\` using a regular expression;
* replace the LaTeX space preceded by the backslash with a usual space.

### CODE REVIEW

**Comment by misharash** [comment]
The build checks seem to have failed due to a deprecated Ubuntu version, fixed that in a new commit (and also increased the Python 3 version).

**Comment by misharash** [comment]
Apparently [Python 2.7 is no longer supported in GitHub Actions](https://github.com/actions/setup-python/issues/672) either. Tried to fix the build by removing it and adding a few more Python 3 versions.

**Comment by kadrlica** [comment]
Starting at Python 3.8 is probably fine.

**Comment by misharash** [comment]
Sorry, I am rather new to the workflows. I enabled them in my fork, and will try to make sure it works there first.

**Comment by misharash** [comment]
Finally, the package is built successfully in my fork.

**Review by kadrlica — APPROVED** [review]

**Comment by kadrlica** [comment]
Sorry that this took so long. I also didn't realize that I'd need to approve/launch each workflow for a contributor who was outside the hosting organization. Thanks for all the work debugging the workflow. 

I've approved your PR, so you should be able to go ahead an merge (otherwise I can do it).

**Comment by misharash** [comment]
GitHub says I need write access to this repository to merge PRs, which I don't have.

It also appeared to me that the [added replacement of `\ `](https://github.com/DarkEnergySurvey/mkauthlist/pull/45/commits/239583b7dc29f592e0f3d798bec33de036849024) might have an issue similar to the one with tilde: `\\ ` -> `\ `. On the other hand, it is not clear to me what the correct behavior should be in this case. Moreover, it does not seem very relevant to the names.

**Pull request merged**
